php
<?php
// View : Historical view of sent emails, both transactional and marketing. Each e-mail going through Mailjet is attached to a Campaign. This object is automatically generated by Mailjet.
$mj = new Mailjet($MJ_APIKEY_PUBLIC,$MJ_APIKEY_PRIVATE);
$params = array(
	"method" => "GET",
);
$result = $mj->campaign($params);
if ($mj->_response_code == 200){
   echo "success";
   var_dump($result);
} else {
   echo "error - ".$mj->_response_code;
   var_dump($mj->_response);
}
?>
